spring.application.name=CUSTOMER-SERVICE
server.port=8081
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.cloud.discovery.enabled=true
spring.datasource.url=jdbc:h2:mem:customer-DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.settings.web-allow-others=true
spring.jpa.defer-datasource-initialization=true
eureka.instance.prefer-ip-address=true